name: Deploy to EC2 (test)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER_TEST }}
          key: ${{ secrets.EC2_SSH_KEY_TEST }}
          script: |
            export PATH=$PATH:/usr/local/bin

            cd /var/www/api-restaurant-manager

            git checkout test
            git pull origin test

            npm install
            npm run build

            pm2 start ecosystem.config.js --env test || pm2 reload ecosystem.config.js --env test
            pm2 save
